@startuml EnemyLogic
state "EnemyLogic State" as Nevergreen_EnemyLogic_State {
  state "Alive" as Nevergreen_EnemyLogic_State_Alive {
    state "KnockedBack" as Nevergreen_EnemyLogic_State_Alive_KnockedBack
    state "Wandering" as Nevergreen_EnemyLogic_State_Alive_Wandering
    state "Metamorphosis" as Nevergreen_EnemyLogic_State_Alive_Metamorphosis
    state "Aggroed" as Nevergreen_EnemyLogic_State_Alive_Aggroed
  }
  state "Dead" as Nevergreen_EnemyLogic_State_Dead
}

Nevergreen_EnemyLogic_State_Alive --> Nevergreen_EnemyLogic_State_Alive_KnockedBack : Damage
Nevergreen_EnemyLogic_State_Alive --> Nevergreen_EnemyLogic_State_Dead : Damage
Nevergreen_EnemyLogic_State_Alive_Aggroed --> Nevergreen_EnemyLogic_State_Alive_Aggroed : Age
Nevergreen_EnemyLogic_State_Alive_Aggroed --> Nevergreen_EnemyLogic_State_Alive_Aggroed : Move
Nevergreen_EnemyLogic_State_Alive_Aggroed --> Nevergreen_EnemyLogic_State_Alive_Metamorphosis : Age
Nevergreen_EnemyLogic_State_Alive_KnockedBack --> Nevergreen_EnemyLogic_State_Alive_Aggroed : Age
Nevergreen_EnemyLogic_State_Alive_KnockedBack --> Nevergreen_EnemyLogic_State_Alive_KnockedBack : Age
Nevergreen_EnemyLogic_State_Alive_Metamorphosis --> Nevergreen_EnemyLogic_State_Alive_Metamorphosis : AnimationFinished
Nevergreen_EnemyLogic_State_Alive_Wandering --> Nevergreen_EnemyLogic_State_Alive_Aggroed : PlayerInRange
Nevergreen_EnemyLogic_State_Dead --> Nevergreen_EnemyLogic_State_Dead : AnimationFinished

Nevergreen_EnemyLogic_State_Alive : OnDamage → Damaged, ForceApplied
Nevergreen_EnemyLogic_State_Alive_Aggroed : OnAge → SpawnLarva
Nevergreen_EnemyLogic_State_Alive_Aggroed : OnEnter → AnimationUpdated
Nevergreen_EnemyLogic_State_Alive_Aggroed : OnMove → FlipSprite, ForceApplied
Nevergreen_EnemyLogic_State_Alive_Aggroed : OnPlayerGlobalPositionSync() → PlayerTrackedAt
Nevergreen_EnemyLogic_State_Alive_KnockedBack : OnAge → ForceApplied
Nevergreen_EnemyLogic_State_Alive_Metamorphosis : OnAnimationFinished → ReplaceWithBroodmother
Nevergreen_EnemyLogic_State_Alive_Metamorphosis : OnEnter → AnimationUpdated
Nevergreen_EnemyLogic_State_Dead : OnAnimationFinished → Died
Nevergreen_EnemyLogic_State_Dead : OnEnter → AnimationUpdated

[*] --> Nevergreen_EnemyLogic_State_Alive_Wandering
@enduml