@startuml EnemyLogic
state "EnemyLogic State" as Woodblight_EnemyLogic_State {
  state "Alive" as Woodblight_EnemyLogic_State_Alive {
    state "KnockedBack" as Woodblight_EnemyLogic_State_Alive_KnockedBack
    state "Wandering" as Woodblight_EnemyLogic_State_Alive_Wandering
    state "Metamorphosis" as Woodblight_EnemyLogic_State_Alive_Metamorphosis
    state "Aggroed" as Woodblight_EnemyLogic_State_Alive_Aggroed
  }
  state "Dead" as Woodblight_EnemyLogic_State_Dead
}

Woodblight_EnemyLogic_State_Alive --> Woodblight_EnemyLogic_State_Alive_KnockedBack : Damage
Woodblight_EnemyLogic_State_Alive --> Woodblight_EnemyLogic_State_Dead : Damage
Woodblight_EnemyLogic_State_Alive_Aggroed --> Woodblight_EnemyLogic_State_Alive_Aggroed : Age
Woodblight_EnemyLogic_State_Alive_Aggroed --> Woodblight_EnemyLogic_State_Alive_Aggroed : Move
Woodblight_EnemyLogic_State_Alive_Aggroed --> Woodblight_EnemyLogic_State_Alive_Metamorphosis : Age
Woodblight_EnemyLogic_State_Alive_KnockedBack --> Woodblight_EnemyLogic_State_Alive_Aggroed : Age
Woodblight_EnemyLogic_State_Alive_KnockedBack --> Woodblight_EnemyLogic_State_Alive_KnockedBack : Age
Woodblight_EnemyLogic_State_Alive_Metamorphosis --> Woodblight_EnemyLogic_State_Alive_Metamorphosis : AnimationFinished
Woodblight_EnemyLogic_State_Alive_Wandering --> Woodblight_EnemyLogic_State_Alive_Aggroed : PlayerInRange
Woodblight_EnemyLogic_State_Dead --> Woodblight_EnemyLogic_State_Dead : AnimationFinished

Woodblight_EnemyLogic_State_Alive : OnDamage → Damaged, ForceApplied
Woodblight_EnemyLogic_State_Alive_Aggroed : OnAge → SpawnLarva
Woodblight_EnemyLogic_State_Alive_Aggroed : OnEnter → AnimationUpdated
Woodblight_EnemyLogic_State_Alive_Aggroed : OnMove → FlipSprite, ForceApplied
Woodblight_EnemyLogic_State_Alive_Aggroed : OnPlayerGlobalPositionSync() → PlayerTrackedAt
Woodblight_EnemyLogic_State_Alive_KnockedBack : OnAge → ForceApplied
Woodblight_EnemyLogic_State_Alive_Metamorphosis : OnAnimationFinished → ReplaceWithBroodmother
Woodblight_EnemyLogic_State_Alive_Metamorphosis : OnEnter → AnimationUpdated
Woodblight_EnemyLogic_State_Dead : OnAnimationFinished → Died
Woodblight_EnemyLogic_State_Dead : OnEnter → AnimationUpdated

[*] --> Woodblight_EnemyLogic_State_Alive_Wandering
@enduml