@startuml GameOverScreenLogic
state "GameOverScreenLogic State" as Nevergreen_GameOverScreenLogic_State

Nevergreen_GameOverScreenLogic_State --> Nevergreen_GameOverScreenLogic_State : ClickToMainMenu

Nevergreen_GameOverScreenLogic_State : OnClickToMainMenu → Hide
Nevergreen_GameOverScreenLogic_State : OnEnter → Hide
Nevergreen_GameOverScreenLogic_State : OnGameOver() → Show

[*] --> Nevergreen_GameOverScreenLogic_State
@enduml