@startuml GameOverScreenLogic
state "GameOverScreenLogic State" as Woodblight_GameOverScreenLogic_State

Woodblight_GameOverScreenLogic_State --> Woodblight_GameOverScreenLogic_State : ClickToMainMenu

Woodblight_GameOverScreenLogic_State : OnClickToMainMenu → Hide
Woodblight_GameOverScreenLogic_State : OnEnter → Hide
Woodblight_GameOverScreenLogic_State : OnGameOver() → Show

[*] --> Woodblight_GameOverScreenLogic_State
@enduml