@startuml PlayerLogic
state "PlayerLogic State" as Woodblight_PlayerLogic_State {
  state "Alive" as Woodblight_PlayerLogic_State_Alive {
    state "Moving" as Woodblight_PlayerLogic_State_Alive_Moving
    state "Attacking" as Woodblight_PlayerLogic_State_Alive_Attacking
    state "Idle" as Woodblight_PlayerLogic_State_Alive_Idle
  }
  state "Dead" as Woodblight_PlayerLogic_State_Dead
}

Woodblight_PlayerLogic_State --> Woodblight_PlayerLogic_State : UpdateGlobalPosition
Woodblight_PlayerLogic_State --> Woodblight_PlayerLogic_State_Alive_Idle : Revive
Woodblight_PlayerLogic_State_Alive --> Woodblight_PlayerLogic_State_Alive : Damage
Woodblight_PlayerLogic_State_Alive --> Woodblight_PlayerLogic_State_Alive_Attacking : Attack
Woodblight_PlayerLogic_State_Alive --> Woodblight_PlayerLogic_State_Dead : Die
Woodblight_PlayerLogic_State_Alive_Attacking --> Woodblight_PlayerLogic_State_Alive_Attacking : AnimationFinished
Woodblight_PlayerLogic_State_Alive_Attacking --> Woodblight_PlayerLogic_State_Alive_Attacking : UpdateHitting
Woodblight_PlayerLogic_State_Alive_Attacking --> Woodblight_PlayerLogic_State_Alive_Idle : AnimationFinished
Woodblight_PlayerLogic_State_Alive_Idle --> Woodblight_PlayerLogic_State_Alive_Idle : Move
Woodblight_PlayerLogic_State_Alive_Idle --> Woodblight_PlayerLogic_State_Alive_Moving : Move
Woodblight_PlayerLogic_State_Alive_Moving --> Woodblight_PlayerLogic_State_Alive_Idle : Move
Woodblight_PlayerLogic_State_Alive_Moving --> Woodblight_PlayerLogic_State_Alive_Moving : Move

Woodblight_PlayerLogic_State : OnPlayerReset() → Teleport
Woodblight_PlayerLogic_State : OnPlayerTeleportationRequested() → Teleport
Woodblight_PlayerLogic_State_Alive : OnDamage → Damaged
Woodblight_PlayerLogic_State_Alive_Attacking : OnEnter → AnimationUpdated, FlipSprite, StartAttacking
Woodblight_PlayerLogic_State_Alive_Attacking : OnExit → FinishedAttacking
Woodblight_PlayerLogic_State_Alive_Attacking : OnUpdateHitting → SetHitting
Woodblight_PlayerLogic_State_Alive_Idle : OnEnter → AnimationUpdated
Woodblight_PlayerLogic_State_Alive_Moving : OnEnter → AnimationUpdated
Woodblight_PlayerLogic_State_Alive_Moving : OnMove → FlipSprite, ForceApplied

[*] --> Woodblight_PlayerLogic_State_Alive_Idle
@enduml