@startuml RoomLogic
state "RoomLogic State" as Woodblight_RoomLogic_State {
  state "Infested" as Woodblight_RoomLogic_State_Infested
  state "Cleared" as Woodblight_RoomLogic_State_Cleared
}

Woodblight_RoomLogic_State_Infested --> Woodblight_RoomLogic_State_Cleared : Clear

Woodblight_RoomLogic_State_Cleared : OnEnter → RemoveBlockage

[*] --> Woodblight_RoomLogic_State_Infested
@enduml