@startuml EnemyLogic
state "EnemyLogic State" as Nevergreen_EnemyLogic_State

Nevergreen_EnemyLogic_State --> Nevergreen_EnemyLogic_State : OnPlayerTouched

Nevergreen_EnemyLogic_State : OnOnPlayerTouched → Damaged
Nevergreen_EnemyLogic_State : OnPlayerGlobalPositionSync() → PlayerTrackedAt

[*] --> Nevergreen_EnemyLogic_State
@enduml