@startuml AppLogic
state "AppLogic State" as Woodblight_AppLogic_State {
  state "LeavingGame" as Woodblight_AppLogic_State_LeavingGame
  state "InMainMenu" as Woodblight_AppLogic_State_InMainMenu
  state "StartingNewGame" as Woodblight_AppLogic_State_StartingNewGame
  state "LeavingMenu" as Woodblight_AppLogic_State_LeavingMenu
  state "ClosingApplication" as Woodblight_AppLogic_State_ClosingApplication
  state "InGame" as Woodblight_AppLogic_State_InGame
}

Woodblight_AppLogic_State --> Woodblight_AppLogic_State : FadeOutFinished
Woodblight_AppLogic_State_ClosingApplication --> Woodblight_AppLogic_State_ClosingApplication : FadeOutFinished
Woodblight_AppLogic_State_InGame --> Woodblight_AppLogic_State_ClosingApplication : QuitApp
Woodblight_AppLogic_State_InGame --> Woodblight_AppLogic_State_LeavingGame : BackToMainMenu
Woodblight_AppLogic_State_InMainMenu --> Woodblight_AppLogic_State_ClosingApplication : QuitApp
Woodblight_AppLogic_State_InMainMenu --> Woodblight_AppLogic_State_LeavingMenu : StartGame
Woodblight_AppLogic_State_LeavingGame --> Woodblight_AppLogic_State_ClosingApplication : FadeOutFinished
Woodblight_AppLogic_State_LeavingGame --> Woodblight_AppLogic_State_InMainMenu : FadeOutFinished
Woodblight_AppLogic_State_LeavingMenu --> Woodblight_AppLogic_State_StartingNewGame : FadeOutFinished
Woodblight_AppLogic_State_StartingNewGame --> Woodblight_AppLogic_State_InGame : GameReady

Woodblight_AppLogic_State : OnAppFadeInRequested() → FadeIn
Woodblight_AppLogic_State : OnAppFadeOutRequested() → FadeOut
Woodblight_AppLogic_State_ClosingApplication : OnEnter → FadeOut
Woodblight_AppLogic_State_ClosingApplication : OnFadeOutFinished → CloseApplication
Woodblight_AppLogic_State_InGame : OnEnter → FadeIn, ShowGame
Woodblight_AppLogic_State_InMainMenu : OnEnter → ShowMainMenu
Woodblight_AppLogic_State_LeavingGame : OnEnter → FadeOut
Woodblight_AppLogic_State_LeavingGame : OnExit → FadeIn, RemoveGame
Woodblight_AppLogic_State_LeavingMenu : OnEnter → FadeOut
Woodblight_AppLogic_State_LeavingMenu : OnExit → HideMainMenu
Woodblight_AppLogic_State_StartingNewGame : OnEnter → SetupGame

[*] --> Woodblight_AppLogic_State_InMainMenu
@enduml